#!/bin/bash

if [[ -d /opt/cuda/include/CL ]]; then
  export OpenCL_INCLUDE_DIR=/opt/cuda/include
fi

if [[ ! -d build ]]; then
  mkdir build
  cd build
  cmake ..
  cd ..
fi
cd build
make >&2
res=$?
cd ..
[[ $res != 0 ]] && exit $res
build/crhash "$@"
